services:
  db:
    image: postgres:16
    container_name: test_db
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: test_api
    ports:
      - "5435:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data